version: '3.6'
volumes:
  registry-data:
networks:
  dev:
    external:
      name: dev
services:
  registry:
    image: registry:2
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/wildcard.crt
      REGISTRY_HTTP_TLS_KEY: /certs/wildcard.key
    ports:
      - 1443:443
    volumes:
      - type: 'bind'
        source: /usr/local/certs
        target: /certs
        volume:
          nocopy: true
      - type: 'volume'
        source: registry-data
        target: /var/lib/registry
        volume:
          nocopy: true
      - type: 'bind'
        source: ./config.yaml
        target: /etc/docker/registry/config.yml
    restart: always
    networks:
      dev:
        aliases:
          - registry
