services:
  registry:
    image: registry:2
    restart: always
    volumes:
      - "./registry/config.yaml:/etc/docker/registry/config.yml:ro"

  links:
    image: nginx:latest
    restart: always
    volumes:
      - "./nginx/html:/usr/share/nginx/html:ro"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: ["start", "--all", "--config", "/etc/ngrok.yml" ]
    volumes:
      - "./ngrok.yml:/etc/ngrok.yml"
