version: '3'

services:
  registry:
    image: registry:2
    volumes:
      - type: 'bind'
        source: ./registry-config.yaml
        target: /etc/docker/registry/config.yml
    restart: always

  links:
    image: nginx:latest
    volumes:
      - type: 'bind'
        source: ./work-links
        target: /usr/share/nginx/html
        read_only: true
      - type: 'bind'
        source: "./nginx.conf"
        target: "/etc/nginx/conf.d/default.conf"
        read_only: true
    restart: always