version: '3'
services:
  dbserver:
    image: "mysql:5.7"
    command: > 
      --max-allowed-packet=536870912
      --sql-mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      --collation-server=utf8mb4_unicode_520_ci
      --character-set-server=utf8mb4
      --lower-case-table-names=1
      --default-time-zone=+00:00
      --tls-version=TLSv1.2
      --ssl-ca=dakcs-ca.crt
      --ssl-cert=dev.crt
      --ssl-key=dev.rsa
    environment:
      MYSQL_ROOT_PASSWORD: "Sting!@#"
    ports:
      - "4406:3306"
    volumes:
      - type: "bind"
        source: ./data
        target: /var/lib/mysql
    restart: always